//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerOnboardingApplication.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public string MembershipNumber { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string AlternativeNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string NationalIdNumber { get; set; }
        public string TaxPIN { get; set; }
        public string Address { get; set; }
        public byte[] Photo { get; set; }
        public string Password { get; set; }
        public string SourceOfIncome { get; set; }
        public string Employer { get; set; }
        public string JobPosition { get; set; }
        public string PayrollNumber { get; set; }
        public string EmployerAddress { get; set; }
        public string EmployerTelephoneNumber { get; set; }
        public double GrossMonthlyIncome { get; set; }
        public System.DateTime DateJoined { get; set; }
        public string MembershipStatus { get; set; }
        public string MembershipType { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    }
}
