//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerOnboardingApplication.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemuser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string WindowsUsername { get; set; }
        public string RoleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string IdNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Status { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
    }
}
